sudo: false
cache: pip

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  # For tests running git command
  - git config --global user.name "test"
  - git config --global user.email "test.test@test.com"

# command to install dependencies
install:
  - pip install .
  - pip install coveralls
  - pip install flake8

# command to run tests
script:
  - git --version
  - flake8 . --exclude=__init__.py
  - coverage run --source git_aggregator setup.py test

after_success:
  - coveralls

deploy:
  provider: pypi
  user: acsbidoul
  password:
    secure: LGD5/HQLvHCV9BRaPF2J73Qs6OBnlA4iDL78Wab9TRPG1Wi8SfuuG2h3tOgHVfVtTOZKA6dhyAQF07/K5sp/fvvOlVp1og9Dda8s1gUhKSb9JRal37fukm7bTfUZQPXlZrC/Xmnw+CRPRcEfRfFzHv3827pxnC9LSktU1kwvl2VkeQ+nrFhmOvhkE+IK8aTHlRA18zZOA3PZLwEJQWuxxbK3/MK6Z5LTokMVIXNZncaammY/aAtzPHdz+W5PPSGAOSEMGzu80Oql+6eRzf9pPNquejZ1aNP1zPlKg939+FCL+DP6D9XXeB+xe31JWeaA5ZUeR4KnyF1n7Cz4Gge8c4H6nYGLayZErxLY/jRVc/mfwofipmN54pUUm/6cAt7ROFL/BlL3QHWZQRKRff0VWP36B4vhP7lHLpePH3EJWvD1VW08sQzcSbiicNk1jVb+VBou4L5PwvLJ1CFGjBjpxpVn3me1KQZaFzr9l8MlJXR4Ikf4FJOMJw06erPmlRPUd9F+KhYHEb3/MawH8cp2pwzxswen4gOXIHbCyP/uuUEadDVL7mEfr1zgxqCfsO/OB4pf9DX/AVCI+QLx1ekJQx/NMQmIxe6ssmFJsF/TX9hqG02YrW/vnx1NQiIhuDueRJ0ippPYH01wDMvsf42z+PAPUxhexnK2/gGf0hj9JQE=
  distributions: "sdist bdist_wheel"
  skip_upload_docs: true
  on:
    repo: acsone/git-aggregator
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
